language: node_js
node_js:
  - "6"
  - "4"
  - "7"
  - "0.12"
before_install:
  - npm install -g npm@latest
sudo: false
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
